name:      "Jacob & the Good Vibes"
bio:       "SoCal-based reggae fusion band blending R&B soul and Latin grooves, known for high-energy live performances and tight, dynamic musicianship. Check below for booking, music, and upcoming shows."
photoURL:  "photo.png"

social: # User IDs only — leave blank to hide a platform, reorder as you like.
  instagram:   "jacob_and_thegoodvibes"
  spotify:     "40ewy6TdcihVbpBzB9zOgE"
  youtube:     "@jacobandthegoodvibes"
  apple:       "jacob-the-good-vibes/1679026261" # requires the numerical identifier after the text name, ex: [username]/1679026261
  amazon:      "B0BZJXYBX7/jacob-the-good-vibes" # requires the amazon identifier before the text name, ex: B0BZJXYBX7/[username]
  threads:     ""
  linkedin:    ""
  discord:     ""
  soundcloud:  ""
  tiktok:      ""
  facebook:    ""
  twitter:     ""
  merch:       ""
  email:       "jacobandthegoodvibes@gmail.com"

emailSubject:  "Booking Inquiry via LinkHUB"

callouts:
  - type: merch
    id: "javascript:alert('COMING SOON!!')"
  - type: spotify
    id: "1gsRgmkHhzR2l3lVJDnrwg"
  - type: youtube
    id: "cn3zEuut3RY"

### ADVANCED FEATURES #####
# google calendar to pull events from:
calendar:  "fc1f1d7fdfebccaeecc2de5b9542e2b138b1bceed4515e24f219b07187045b48@group.calendar.google.com"
# google analytics account to track interactions with
analytics: ""

